app:
  host: 0.0.0.0
  port: 7070
  router_prefix: api/v1
  jwt_secret: 

database:
  host: 127.0.0.1
  port: 3306
  username: 
  password: 
  dbname: rache_familyfinacialmanager

email:
  smtp_host: 
  smtp_port: 
  account: 
  password: 
  from_email: 
  enabled: true