CREATE TABLE Users (
    UserID INT AUTO_INCREMENT PRIMARY KEY COMMENT '用户ID',
    UUID CHAR(36) NOT NULL UNIQUE COMMENT '用户唯一标识，用于API返回',
    UserName VARCHAR(50) NOT NULL UNIQUE COMMENT '用户名',
    Password VARCHAR(255) NOT NULL COMMENT '加密密码',
    Email VARCHAR(100) UNIQUE COMMENT '用户邮箱',
    FamilyID INT DEFAULT NULL COMMENT '所属家庭ID',
    Token VARCHAR(255) COMMENT '登录token，用于自动登录',
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间',
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    CONSTRAINT FK_User_Family FOREIGN KEY (FamilyID) REFERENCES Family(FamilyID)
        ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';

CREATE TABLE Family (
    FamilyID INT AUTO_INCREMENT PRIMARY KEY COMMENT '家庭编号',
    FamilyName VARCHAR(100) NOT NULL COMMENT '家庭名称',
    Address VARCHAR(255) COMMENT '住址',
    Contact VARCHAR(100) COMMENT '联系方式',
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='家庭信息表';

CREATE TABLE Member (
    MemberID INT AUTO_INCREMENT PRIMARY KEY COMMENT '成员编号',
    FamilyID INT NOT NULL COMMENT '所属家庭编号',
    UserID INT DEFAULT NULL COMMENT '关联用户ID，可为空表示未注册成员',
    Name VARCHAR(50) NOT NULL COMMENT '成员姓名',
    Email VARCHAR(100) COMMENT '邮箱，用于邀请',
    Status ENUM('pending','accepted') DEFAULT 'accepted' COMMENT '邀请状态',
    Gender ENUM('男','女','其他') COMMENT '性别',
    Age INT COMMENT '年龄',
    Relation VARCHAR(50) COMMENT '与家庭关系（父亲、母亲、子女等）',
    CONSTRAINT FK_Member_Family FOREIGN KEY (FamilyID) REFERENCES Family(FamilyID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_Member_User FOREIGN KEY (UserID) REFERENCES Users(UserID)
        ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='家庭成员表';

CREATE TABLE Category (
    CategoryID INT AUTO_INCREMENT PRIMARY KEY COMMENT '分类编号',
    CategoryName VARCHAR(100) NOT NULL COMMENT '分类名称',
    Type ENUM('收入','支出') NOT NULL COMMENT '分类类型',
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='收支分类表';

CREATE TABLE TransactionRecord (
    TransactionID INT AUTO_INCREMENT PRIMARY KEY COMMENT '收支记录编号',
    FamilyID INT NOT NULL COMMENT '所属家庭编号',
    MemberID INT DEFAULT NULL COMMENT '成员编号，可为空表示家庭整体',
    CategoryID INT NOT NULL COMMENT '分类编号',
    Type ENUM('收入','支出') NOT NULL COMMENT '收支类型',
    Amount DECIMAL(10,2) NOT NULL COMMENT '金额',
    OccurredAt DATETIME NOT NULL COMMENT '发生时间',
    Note VARCHAR(255) COMMENT '备注',
    Merchant VARCHAR(100) COMMENT '商家名称（可选）',
    Location VARCHAR(100) COMMENT '消费地点（可选）',
    PaymentMethod VARCHAR(50) COMMENT '支付方式（现金/银行卡/微信/支付宝等）',
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
    CONSTRAINT FK_Transaction_Family FOREIGN KEY (FamilyID) REFERENCES Family(FamilyID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_Transaction_Member FOREIGN KEY (MemberID) REFERENCES Member(MemberID)
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT FK_Transaction_Category FOREIGN KEY (CategoryID) REFERENCES Category(CategoryID)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='家庭收支记录表';

CREATE TABLE RecurringTransaction (
    RecurringID INT AUTO_INCREMENT PRIMARY KEY COMMENT '定期账单ID',
    FamilyID INT NOT NULL COMMENT '所属家庭ID',
    MemberID INT DEFAULT NULL COMMENT '成员ID',
    CategoryID INT NOT NULL COMMENT '分类ID',
    Type ENUM('收入','支出') NOT NULL COMMENT '账单类型',
    Amount DECIMAL(10,2) NOT NULL COMMENT '账单金额',
    OccurredAt DATETIME NOT NULL COMMENT '第一次发生时间',
    IntervalType ENUM('daily','weekly','monthly') NOT NULL COMMENT '周期类型',
    Note VARCHAR(255) COMMENT '备注',
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    CONSTRAINT FK_Recurring_Family FOREIGN KEY (FamilyID) REFERENCES Family(FamilyID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_Recurring_Member FOREIGN KEY (MemberID) REFERENCES Member(MemberID)
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT FK_Recurring_Category FOREIGN KEY (CategoryID) REFERENCES Category(CategoryID)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='定期账单表';

CREATE TABLE Budget (
    BudgetID INT AUTO_INCREMENT PRIMARY KEY COMMENT '预算ID',
    FamilyID INT NOT NULL COMMENT '所属家庭ID',
    CategoryID INT DEFAULT NULL COMMENT '对应分类，可为空表示整体预算',
    Amount DECIMAL(10,2) NOT NULL COMMENT '预算金额',
    StartDate DATE NOT NULL COMMENT '预算开始日期',
    EndDate DATE DEFAULT NULL COMMENT '预算结束日期',
    Note VARCHAR(255) COMMENT '备注',
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    CONSTRAINT FK_Budget_Family FOREIGN KEY (FamilyID) REFERENCES Family(FamilyID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_Budget_Category FOREIGN KEY (CategoryID) REFERENCES Category(CategoryID)
        ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='家庭预算表';